### ISSUE TITLE
Various streams are now bytes

### ISSUE THREAD

**Issue by local-minimum** [Scan-o-Matic/scanomatic-standalone#39]
# 📋 Info

They used to be strings, and things will probably not work

# 🏁 DoD

- [ ] check all io... 😓

**Comment by local-minimum** [comment]
Example:
```
scanomatic_1  | Traceback (most recent call last):
scanomatic_1  |   File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
scanomatic_1  |     self.run()
scanomatic_1  |   File "/usr/local/lib/python3.9/threading.py", line 910, in run
scanomatic_1  |     self._target(*self._args, **self._kwargs)
scanomatic_1  |   File "/usr/local/lib/python3.9/site-packages/scanomatic/server/server.py", line 134, in _run
scanomatic_1  |     self._jobs.sync()
scanomatic_1  |   File "/usr/local/lib/python3.9/site-packages/scanomatic/server/jobs.py", line 141, in sync
scanomatic_1  |     self.handle_scanners()
scanomatic_1  |   File "/usr/local/lib/python3.9/site-packages/scanomatic/server/jobs.py", line 150, in handle_scanners
scanomatic_1  |     self._scanner_manager.update()
scanomatic_1  |   File "/usr/local/lib/python3.9/site-packages/scanomatic/io/scanner_manager.py", line 385, in update
scanomatic_1  |     alive_scanners = get_alive_scanners()
scanomatic_1  |   File "/usr/local/lib/python3.9/site-packages/scanomatic/io/sane.py", line 25, in get_alive_scanners
scanomatic_1  |     return re.findall(
scanomatic_1  |   File "/usr/local/lib/python3.9/re.py", line 241, in findall
scanomatic_1  |     return _compile(pattern, flags).findall(string)
scanomatic_1  | TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by skymandr** [comment]
Some, but not all, of this is done.
