### ISSUE TITLE
Validate can do QC

### ISSUE THREAD

**Issue by local-minimum** [Scan-o-Matic/scanomatic-standalone#47]
# 📋 Info
**Partially blocked** by #46 

Do various QC tasks on project

# 🏁 DoD

- [x] New project from #46
- [x] Old project from python 2.7 times

**Comment by skymandr** [comment]
Found when loading a complete converted project in #99:
```console
ERROR	**Scan-o-Matic UI** Exception on /api/results/phenotype_names/PM2/PayamMartin19Oct16Scanner2/analysis_original [GET]

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/scanomatic/ui_server/qc_api.py", line 705, in get_phenotype_names
    state, _ = _get_state_update_response(path, response, success=True)
  File "/usr/local/lib/python3.9/site-packages/scanomatic/ui_server/qc_api.py", line 69, in _get_state_update_response
    state = phenotyper.Phenotyper.LoadFromState(path)
  File "/usr/local/lib/python3.9/site-packages/scanomatic/data_processing/phenotyper.py", line 354, in LoadFromState
    PhenotypeDataType[inclusion_name],
  File "/usr/local/lib/python3.9/enum.py", line 432, in __getitem__
    return cls._member_map_[name]
KeyError: b'Trusted'
```

**Comment by local-minimum** [comment]
The issue there seems to be that it is loaded as bytes while since it should load as an enum value must be string format.
